services:
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file: .env
    ports:
          - 443:443

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file: .env
    volumes: 
      - /home/vsergio/data/wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes: 
      - /home/vsergio/data/db:/var/lib/mysql


## see if it's necessary to use the structure below or we can use
## volume directly from the services
volumes:

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
            device: /home/vsergio/data/wordpress
            o: bind
            type: none
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
            device: /home/vsergio/data/mariadb
            o: bind
            type: none
