services:

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    # image: nginx
    restart: always
    env_file: .env
    ports:
      - 443:443
    # NGINX need read the files from wordpress, to load the website.
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    # image: wordpress
    restart: always
    env_file: .env
    ports:
      - 9000:9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    # image: mariadb
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

volumes:

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
            type: none
            device: /Users/vitor/data/wordpress
            o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
            type: none
            device: /Users/vitor/data/mariadb
            o: bind


networks:
  inception:
    name: inception
